name: updater:
  schedule:
    - cron: '* * 6 * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Pull in last 5 blog posts
        uses: rajbos-actions/blog-post-workflow@master
        with:
          feed_list: "https://devopsjournal.io/blog/atom.xml"
          max_post_count: 5
