name: Updater
on:  
  schedule:
    - cron: '5 23 * * *'
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/updater.yml

permissions: read-all

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    permissions: 
      contents: write # needed to be able to post the RSS updates
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            devopsjournal.io:443          

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        
      - name: Pull in last 5 blog posts
        uses: rajbos-actions/blog-post-workflow@6da0638f66000902e4eb30ce05ed6a9d160c0c05 # master
        with:
          feed_list: "https://devopsjournal.io/blog/atom.xml"
          max_post_count: 5
